#! /usr/bin/env bash

has_cmd() {
    for opt in "$@"; do
        if command -v "$opt" >/dev/null; then
            continue
        else
            return $?
        fi
    done
}

mime=$(file -Lbs --mime-type "$1")
category=${mime%%/*}
kind=${mime##*/}
ext=${1##*.}

if [ "$kind" = json ]; then
    if has_cmd jupyter bat && [ "$ext" = ipynb ]; then
        jupyter nbconvert --to python --stdout "$1" | bat --color always --language python

    elif has_cmd jq; then
        jq --color-output --raw-output . "$1"
    fi

elif [ -d "$1" ]; then
    if has_cmd eza; then
        eza --color always --all --header --long --git --icons --group-directories-first "$1"
    fi

else
    if has_cmd bat; then
        bat --color always "$1"
    fi
fi
