wtf:
  colors:
    background: black
    title: lightgreen
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight:
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  refreshInterval: 1
  openFileUtil: open
  grid:
    columns:
      [
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        1000,
      ]
    rows: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1000]
  mods:
    github:
      title: Github
      enabled: true
      refreshInterval: 300
      position:
        top: 0
        left: 0
        width: 5
        height: 6
      apiKey: ~
      baseURL: ~
      uploadURL: ~
      enableStatus: true
      showStats: true
      showMyPullRequests: true
      showOpenReviewRequests: true
      repositories:
        - calgo-lab/green-db
      username: se-jaeger
      customQueries:
        othersPRs:
          title: Pull Requests
          filter: is:open is:pr
        openIssues:
          title: Issues
          filter: is:issue state:open
    ipapi:
      enabled: true
      title: IP
      refreshInterval: 150
      position:
        top: 0
        left: 5
        width: 4
        height: 2
      args:
        - ip
        - isp
        - as
        - city
        - regionName
        - country
    power:
      title: "⚡️"
      enabled: true
      refreshInterval: 60
      position:
        top: 0
        left: 9
        width: 4
        height: 2
    prettyweather:
      enabled: true
      refreshInterval: 5m
      title: ☀️
      position:
        top: 2
        left: 5
        width: 8
        height: 4
      city: "Berlin"
      unit: m
      view: FQ1n
      language: de
    hackernews:
      enabled: true
      refreshInterval: 15m
      position:
        top: 0
        left: 13
        height: 2
        width: 7
      numberOfStories: 10
      storyType: top
    resourceusage:
      enabled: true
      refreshInterval: 1s
      position:
        top: 2
        left: 13
        height: 4
        width: 4
      cpuCombined: false
      showCPU: true
      showMem: true
      showSwp: true
