[mgr]
prepend_keymap = [
  # Use d to cut files
  { on = "d", run = "yank --cut", desc = "Cut selected files" },

  # Use x to trash files
  { on = "x", run = "remove", desc = "Trash selected files" },

  # Drop to shell
  { on = "!", for = "unix", run = 'shell "$SHELL" --block', desc = "Open $SHELL here" },

  # Use ? to open help
  { on = "?", run = "help", desc = "Open help" },
]
