theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
bufferline = "multiple"
end-of-line-diagnostics = "hint"
scrolloff = 20
clipboard-provider = "termcode"
completion-replace = true

[editor.whitespace]
render = "all"

[editor.statusline]
center = ["workspace-diagnostics"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

################
# Key Mappings #
[keys.normal]
"space".q.q = ":quit"
"space".q.f = ":quit!"
C-s = ":write"
C-j = "save_selection"

# use yazi as file-picker
"-" = [
    ':run-shell-command rm -f /tmp/unique-file',
    ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
    ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
    ':open %sh{cat /tmp/unique-file}',
    ':redraw',
]

# Latex bindings
# NOTE: Assuming justfile exists that implements recipes.
# HACK: harper-ls does not work with tex files. This script temporarily renames it.
"space".t.l = [
    ":write-all",
    ":run-shell-command just lint",
    ":buffer-close-all",
]
"space".t.c = [
    ":run-shell-command just clean",
]
"space".t.b = [
    ":write-all",
    ":run-shell-command just",
]
