theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
bufferline = "multiple"
scrolloff = 20
clipboard-provider = "termcode"
completion-replace = true

[editor.word-completion]
enable = true
trigger-length = 3

[editor.statusline]
center = ["workspace-diagnostics"]

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

## #############
# Key Mappings #

[keys.normal]
C-s = ":write"
C-j = "save_selection"
# use yazi as file-picker
"-" = [
  ":run-shell-command rm -f /tmp/unique-file",
  ":insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file",
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ":open %sh{cat /tmp/unique-file}",
  ":redraw",
]

# 'quit' minor mode
[keys.normal."space".q]
q = ":quit"
f = ":quit!"

# 'config' minor mode
[keys.normal."space".c]
w = ":toggle-option soft-wrap.enable"

# 'latex' minor mode
[keys.normal."space".t]
# NOTE: Assuming justfile exists that implements recipes.
c = [
  ":run-shell-command just clean",
]
b = [
  ":write-all",
  ":run-shell-command just",
]
