[[sources]]
name = "friendly-snippets"
git = "https://github.com/rafamadriz/friendly-snippets.git"

[[sources.paths]]
scope = ["python"]
path = "snippets/python/comprehension.json"

[[sources.paths]]
scope = ["python"]
path = "snippets/python/pydoc.json"

[[sources.paths]]
scope = ["python"]
path = "snippets/python/python.json"

[[sources.paths]]
scope = ["latex"]
path = "snippets/latex/latex-snippets.json"

[[sources.paths]]
scope = ["latex"]
path = "snippets/latex/vscode-latex-snippets.json"

[[sources.paths]]
scope = ["rust"]
path = "snippets/rust/rust.json"

[[sources.paths]]
scope = ["rust"]
path = "snippets/rust/rustdoc.json"

[[sources.paths]]
scope = ["git-commit"]
path = "snippets/gitcommit.json"

[[sources.paths]]
scope = ["markdown", "markdown.inline"]
path = "snippets/markdown.json"
