[[language]]
name = "python"
language-servers = ["ty", "ruff", "codebook", "harper-ls"]
auto-format = true

[language.formatter]
command = "sh"
args = [
  "-c",
  # We typically do both fix linting issues and format
  "ruff check --fix - | ruff format -",
]

[[language]]
name = "git-commit"
language-servers = ["codebook", "harper-ls"]

[[language]]
name = "jjdescription"
language-servers = ["codebook", "harper-ls"]

[[language]]
name = "markdown"
language-servers = ["rumdl", "zettelkasten", "codebook", "harper-ls"]
auto-format = true

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "codebook", "harper-ls"]

[[language]]
name = "toml"
language-servers = ["tombi", "codebook", "harper-ls"]
auto-format = true

[[language]]
name = "latex"
language-servers = ["texlab", "codebook", "harper-ls"]

## #######################
# Set up additional LSPs #
[language-server.texlab.config.texlab]
formatterLineLength = 160

[language-server.zettelkasten]
command = "zk"
args = ["lsp"]

[language-server.harper-ls.config.harper-ls.linters]
SpellCheck = false  # We use codebook for this
AnotherThinkComing = true
SpelledNumbers = true
ViciousCycle = true
BoringWords = true
NoOxfordComma = false  # We do not want this
PossessiveNoun = true
ViciousCircleOrCycle = true

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]
