# Start AeroSpace at login
start-at-login = true

# Use JankyBorders to highlight active window
after-startup-command = [
    'exec-and-forget borders style=square active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0',
]

# Mouse follows focus when window changes
on-focus-changed = ['move-mouse window-lazy-center']

accordion-padding = 50

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace q'

[[on-window-detected]]
if.app-id = 'org.mozilla.librewolf'
check-further-callbacks = true
run = 'move-node-to-workspace q'

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = 'move-node-to-workspace w'

[[on-window-detected]]
if.app-id = 'org.mozilla.betterbird'
check-further-callbacks = true
run = 'move-node-to-workspace w'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.bitwarden.desktop'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'org.mozilla.librewolf'
check-further-callbacks = true
if.window-title-regex-substring = '.*bitwarden password manager.*'
run = 'layout floating'

# TODO: Betterbid Popup
[[on-window-detected]]
if.app-id = 'org.mozilla.betterbird'
if.window-title-regex-substring = '.+'
check-further-callbacks = true
run = 'layout floating'

[workspace-to-monitor-force-assignment]
q = 'main'
w = 'secondary'

[gaps]
inner.horizontal = 3
inner.vertical = 3
outer.left = 3
outer.bottom = 3
outer.top = 3
outer.right = 3

[mode.main.binding]
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
#                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
#                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
#                   sectionSign (ISO keyboards only, european keyboards only)
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# Moving focus
ctrl-alt-shift-h = 'focus left'
ctrl-alt-shift-j = 'focus down'
ctrl-alt-shift-k = 'focus up'
ctrl-alt-shift-l = 'focus right'

# Moving windows
cmd-ctrl-alt-shift-h = 'move left'
cmd-ctrl-alt-shift-j = 'move down'
cmd-ctrl-alt-shift-k = 'move up'
cmd-ctrl-alt-shift-l = 'move right'

# Joining windows
cmd-ctrl-alt-shift-s = 'join-with left'
cmd-ctrl-alt-shift-f = 'join-with down'
cmd-ctrl-alt-shift-d = 'join-with up'
cmd-ctrl-alt-shift-g = 'join-with right'

# Moving focus to workspace
ctrl-alt-shift-q = 'workspace q'
ctrl-alt-shift-w = 'workspace w'
ctrl-alt-shift-e = 'workspace e'
ctrl-alt-shift-r = 'workspace r'

# Move to workspace
cmd-ctrl-alt-shift-q = 'move-node-to-workspace q'
cmd-ctrl-alt-shift-w = 'move-node-to-workspace w'
cmd-ctrl-alt-shift-e = 'move-node-to-workspace e'
cmd-ctrl-alt-shift-r = 'move-node-to-workspace r'

# Applications
ctrl-alt-shift-a = 'exec-and-forget open -a Ghostty.app'
ctrl-alt-shift-s = 'exec-and-forget open -a LibreWolf.app'
ctrl-alt-shift-d = 'exec-and-forget open -a Betterbird.app'
ctrl-alt-shift-f = 'exec-and-forget open -a "Microsoft Teams.app"'

# Layout operations
cmd-ctrl-alt-shift-t = 'layout tiles horizontal vertical'
cmd-ctrl-alt-shift-a = 'layout accordion horizontal vertical'
cmd-ctrl-alt-shift-v = 'layout floating tiling'
cmd-ctrl-alt-shift-m = 'fullscreen'
cmd-ctrl-alt-shift-c = 'balance-sizes'
cmd-ctrl-alt-shift-i = 'resize smart +20'
cmd-ctrl-alt-shift-o = 'resize smart -20'
