import = [
    # "~/.config/alacritty/themes/catppuccin-latte.toml"
    # "~/.config/alacritty/themes/catppuccin-frappe.toml"
    # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
    # "~/.config/alacritty/themes/catppuccin-mocha.toml"
    # "~/.config/alacritty/themes/gruvbox-dark.toml"
    # "~/.config/alacritty/themes/gruvbox-light.toml"
    "~/.config/alacritty/themes/gruvbox-material.toml",
    # "~/.config/alacritty/themes/gruvbox-material-hard-dark.toml"
    # "~/.config/alacritty/themes/gruvbox-material-hard-light.toml"
    # "~/.config/alacritty/themes/gruvbox-material-medium-dark.toml"
    # "~/.config/alacritty/themes/gruvbox-material-medium-light.toml"
]

[shell]
program = "zsh"
args = ["-l", "-c", "tmux attach || tmux new -s main"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
startup_mode = "Windowed"
decorations_theme_variant = "Dark"
option_as_alt = "Both"

[scrolling]
history = 100000

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 14

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left", mods = "Alt", chars = "\u001BB" },
]
