
[terminal.shell]
program = "fish"
args = ["--command", "zellij attach --create main"]

[window]
decorations = "None"
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
option_as_alt = "Both"
padding = { x = 3, y = 0 }

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 14

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left", mods = "Alt", chars = "\u001BB" },
]
