[user]
name = "Sebastian Jäger"
email = "github@sebastian-jaeger.me"

[ui]
default-command = ["log"]

[signing]
backend = "gpg"
key = "3608F3D413836957"

[template-aliases]
prompt = '''
  separate(
    " ",
    change_id.shortest(4),
    if(! empty, ">"),
    if(! empty, 
        "[" ++ raw_escape_sequence("\x1b[1;34m") ++ diff.files().len() ++ " "
        ++ raw_escape_sequence("\x1b[1;32m") ++ "+" ++ diff.stat().total_added()
        ++ raw_escape_sequence("\x1b[1;31m") ++ "-" ++ diff.stat().total_removed()
        ++ raw_escape_sequence("\x1b[0m")
        ++ "]"
    ),
    if(bookmarks.len() > 0, ">"),
    bookmarks,
    if(conflict || divergent || hidden || immutable, ">"),
    concat(
      if(conflict, "💥"),
      if(divergent, "🚧"),
      if(hidden, "👻"),
      if(immutable, "🔒"),
    ),
    if(description.len() > 0, ">"),
    if(description.len() > 0, concat(
        raw_escape_sequence("\x1b[1;32m"), 
        '"',
        truncate_end(29, description.first_line(), "…"),
        '"',
        raw_escape_sequence("\x1b[0m"),
      )
    ),
  )
'''
