version: "0.2"
language: "en"
dictionaries:
  - custom-words
  # the following are pre-defined
  - python
  - bash
  - docker
  - filetypes
  - git
  - k8s
  - makefile
  - rust
  # the following are not pre-defined
  - data-science
  - de-de
  - markdown
dictionaryDefinitions:
  - name: "custom-words"
    path: "~/.config/cspell/custom-words.txt"
