[tool.ruff]
line-length = 160
target-version = "py39"
fix = true
extend-include = ["*.ipynb"]

[tool.ruff.lint]
select = [
    "ALL", # include all the rules, including new ones
]
ignore = [
    "D100", # Do not document public modules
    "D104", # Do not document public packages
    "TD003", # Allow TODOs without links
    "ISC003", # Do not implicitly concatenate strings
]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = [
    "F401", # unused imports in __init__ files can make sense
]

[tool.ruff.lint.pydocstyle]
convention = "google"
